# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 462)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.removeStudentCBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.removeStudentCBox.setObjectName("removeStudentCBox")
        self.gridLayout.addWidget(self.removeStudentCBox, 2, 3, 1, 1)
        self.studentLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.studentLabel.setObjectName("studentLabel")
        self.gridLayout.addWidget(self.studentLabel, 0, 2, 1, 1)
        self.auStudentLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.auStudentLabel.setObjectName("auStudentLabel")
        self.gridLayout.addWidget(self.auStudentLabel, 3, 2, 1, 1)
        self.removeStudentLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.removeStudentLabel.setObjectName("removeStudentLabel")
        self.gridLayout.addWidget(self.removeStudentLabel, 2, 2, 1, 1)
        self.removeStudentButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.removeStudentButton.setStyleSheet("background-color: rgb(104, 75, 0);\n"
"color: white;")
        self.removeStudentButton.setObjectName("removeStudentButton")
        self.gridLayout.addWidget(self.removeStudentButton, 2, 4, 1, 1)
        self.dodajButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.dodajButton.setStyleSheet("background-color: rgb(90, 229, 47)")
        self.dodajButton.setObjectName("dodajButton")
        self.gridLayout.addWidget(self.dodajButton, 1, 4, 1, 1)
        self.acceptButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.acceptButton.setStyleSheet("background-color: red;\n"
"color: white;\n"
"font-weight: bold;")
        self.acceptButton.setObjectName("acceptButton")
        self.gridLayout.addWidget(self.acceptButton, 4, 3, 1, 2)
        self.auStudentLW = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.auStudentLW.setObjectName("auStudentLW")
        self.gridLayout.addWidget(self.auStudentLW, 3, 3, 1, 2)
        self.studentLW = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.studentLW.setObjectName("studentLW")
        item = QtWidgets.QListWidgetItem()
        self.studentLW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.studentLW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.studentLW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.studentLW.addItem(item)
        self.gridLayout.addWidget(self.studentLW, 0, 3, 1, 2)
        self.addStudent = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.addStudent.setObjectName("addStudent")
        self.gridLayout.addWidget(self.addStudent, 1, 3, 1, 1)
        self.addStudentLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.addStudentLabel.setObjectName("addStudentLabel")
        self.gridLayout.addWidget(self.addStudentLabel, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.studentLabel.setText(_translate("Dialog", "Uczniowie"))
        self.auStudentLabel.setText(_translate("Dialog", "Zaplanowany sierpien"))
        self.removeStudentLabel.setText(_translate("Dialog", "Wybierz uczniow do usuniecia"))
        self.removeStudentButton.setText(_translate("Dialog", "Usuń"))
        self.dodajButton.setText(_translate("Dialog", "Dodaj"))
        self.acceptButton.setText(_translate("Dialog", "Zapisz wyrok"))
        __sortingEnabled = self.studentLW.isSortingEnabled()
        self.studentLW.setSortingEnabled(False)
        item = self.studentLW.item(0)
        item.setText(_translate("Dialog", "Filip \"Łysy\" Pawłowski"))
        item = self.studentLW.item(1)
        item.setText(_translate("Dialog", "Roch \"Kosmiczna sztuczka\" Drgas"))
        item = self.studentLW.item(2)
        item.setText(_translate("Dialog", "Maksymilian \"Frytkarz\" Mainda"))
        item = self.studentLW.item(3)
        item.setText(_translate("Dialog", "Kajetan \"Kasztan\" Kafka"))
        self.studentLW.setSortingEnabled(__sortingEnabled)
        self.addStudentLabel.setText(_translate("Dialog", "Wpisz imie i nazwisko do dodania"))
