# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 462)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.studentLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.studentLabel.setObjectName("studentLabel")
        self.gridLayout.addWidget(self.studentLabel, 0, 0, 1, 1)
        self.studentLW = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.studentLW.setObjectName("studentLW")
        item = QtWidgets.QListWidgetItem()
        self.studentLW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.studentLW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.studentLW.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.studentLW.addItem(item)
        self.gridLayout.addWidget(self.studentLW, 0, 1, 1, 1)
        self.auStudentLW = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.auStudentLW.setObjectName("auStudentLW")
        self.gridLayout.addWidget(self.auStudentLW, 1, 1, 1, 1)
        self.auStudentLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.auStudentLabel.setObjectName("auStudentLabel")
        self.gridLayout.addWidget(self.auStudentLabel, 1, 0, 1, 1)
        self.acceptButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.acceptButton.setStyleSheet("background-color: red;\n"
"color: white;\n"
"font-weight: bold;")
        self.acceptButton.setObjectName("acceptButton")
        self.gridLayout.addWidget(self.acceptButton, 2, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.studentLabel.setText(_translate("Dialog", "Uczniowie"))
        __sortingEnabled = self.studentLW.isSortingEnabled()
        self.studentLW.setSortingEnabled(False)
        item = self.studentLW.item(0)
        item.setText(_translate("Dialog", "Filip \"Łysy\" Pawłowski"))
        item = self.studentLW.item(1)
        item.setText(_translate("Dialog", "Roch \"Kosmiczna sztuczka\" Drgas"))
        item = self.studentLW.item(2)
        item.setText(_translate("Dialog", "Maksymilian \"Frytkarz\" Mainda"))
        item = self.studentLW.item(3)
        item.setText(_translate("Dialog", "Kajetan \"Kasztan\" Kafka"))
        self.studentLW.setSortingEnabled(__sortingEnabled)
        self.auStudentLabel.setText(_translate("Dialog", "Zaplanowany sierpien"))
        self.acceptButton.setText(_translate("Dialog", "Zapisz wyrok"))
